import Mathlib


structure TreeDecomposition {V : Type*} (G : SimpleGraph V) where
  Node : Type*
  T : SimpleGraph Node
  T_istree : T.IsTree
  node2bag : Node -> Set V
  VertexCoverage : ∀ v : V, ∃ n : Node, v ∈ node2bag n
  EdgeCoverage : ∀ {u v : V}, G.Adj u v -> ∃ n : Node, u ∈ node2bag n ∧ v ∈ node2bag n
  Connectivity : ∀ v : V, (T.induce {n : Node | v ∈ node2bag n}).Preconnected

structure RootedTreeDecomposition {V : Type*} (G : SimpleGraph V) where
  decomp : TreeDecomposition G
  root : decomp.Node

namespace TreeDecomposition

variable {V : Type*} {G : SimpleGraph V}

/-- The bag associated with a tree node. -/
def bag (D : TreeDecomposition G) (t : D.Node) : Set V :=
  D.node2bag t

/-- The set of tree nodes whose bags contain a graph vertex. -/
def bagsOf (D : TreeDecomposition G) (v : V) : Set D.Node :=
  {t | v ∈ D.bag t}

@[simp] theorem mem_bagsOf (D : TreeDecomposition G) (v : V) (t : D.Node) :
    t ∈ D.bagsOf v ↔ v ∈ D.bag t :=
  Iff.rfl

/-- Every graph vertex appears in at least one bag. -/
theorem bagsOf_nonempty (D : TreeDecomposition G) (v : V) :
    (D.bagsOf v).Nonempty := by
  rcases D.VertexCoverage v with ⟨t, ht⟩
  exact ⟨t, ht⟩

/-- Every graph edge appears inside at least one bag. -/
theorem exists_bag_of_adj (D : TreeDecomposition G) {u v : V} (h : G.Adj u v) :
    ∃ t : D.Node, u ∈ D.bag t ∧ v ∈ D.bag t := by
  simpa [bag] using D.EdgeCoverage h

/-- The bags containing a fixed graph vertex form a connected part of the tree. -/
theorem bagsOf_preconnected (D : TreeDecomposition G) (v : V) :
    (D.T.induce (D.bagsOf v)).Preconnected := by
  simpa [bagsOf, bag] using D.Connectivity v

end TreeDecomposition

namespace RootedTreeDecomposition

variable {V : Type*} {G : SimpleGraph V}

/-- The bag associated with a tree node. -/
def bag (T : RootedTreeDecomposition G) (t : T.decomp.Node) : Set V :=
  T.decomp.bag t

/-- The set of tree nodes whose bags contain a graph vertex. -/
def bagsOf (T : RootedTreeDecomposition G) (v : V) : Set T.decomp.Node :=
  T.decomp.bagsOf v

@[simp] theorem mem_bagsOf (T : RootedTreeDecomposition G) (v : V) (t : T.decomp.Node) :
    t ∈ T.bagsOf v ↔ v ∈ T.bag t :=
  Iff.rfl

/-- The unique path from the root to a tree node. -/
noncomputable def rootPath (T : RootedTreeDecomposition G) (t : T.decomp.Node) :
    T.decomp.T.Walk T.root t :=
  (T.decomp.T_istree.existsUnique_path T.root t).choose

/-- The chosen root path is simple. -/
theorem rootPath_isPath (T : RootedTreeDecomposition G) (t : T.decomp.Node) :
    (T.rootPath t).IsPath :=
  (T.decomp.T_istree.existsUnique_path T.root t).choose_spec.1

@[simp] theorem rootPath_root (T : RootedTreeDecomposition G) :
    T.rootPath T.root = SimpleGraph.Walk.nil := by
  exact (SimpleGraph.Walk.isPath_iff_eq_nil (T.rootPath T.root)).mp
    (T.rootPath_isPath T.root)

/-- The parent of a node, defined as the penultimate vertex on the root path.
For the root itself this returns the root. -/
noncomputable def parent (T : RootedTreeDecomposition G) (t : T.decomp.Node) : T.decomp.Node :=
  (T.rootPath t).penultimate

@[simp] theorem parent_root (T : RootedTreeDecomposition G) :
    T.parent T.root = T.root := by
  simp [parent]

/-- A non-root node is adjacent to its parent. -/
theorem parent_adj (T : RootedTreeDecomposition G) {t : T.decomp.Node}
    (hroot : t ≠ T.root) :
    T.decomp.T.Adj (T.parent t) t := by
  exact (T.rootPath t).adj_penultimate (SimpleGraph.Walk.not_nil_of_ne hroot.symm)

/-- The child relation induced by the parent function of the rooted tree. -/
def IsChild (T : RootedTreeDecomposition G) (parent child : T.decomp.Node) : Prop :=
  child ≠ T.root ∧ parent = T.parent child

/-- `parent` is the parent of `child` in the rooted tree. -/
def IsParent (T : RootedTreeDecomposition G) (parent child : T.decomp.Node) : Prop :=
  T.IsChild parent child

theorem not_isChild_root (T : RootedTreeDecomposition G) (parent : T.decomp.Node) :
    ¬ T.IsChild parent T.root := by
  intro h
  exact h.1 rfl

theorem IsChild.adj {T : RootedTreeDecomposition G} {parent child : T.decomp.Node}
    (h : T.IsChild parent child) :
    T.decomp.T.Adj parent child := by
  rw [h.2]
  exact T.parent_adj h.1

theorem isChild_parent {T : RootedTreeDecomposition G} {t : T.decomp.Node}
    (hroot : t ≠ T.root) :
    T.IsChild (T.parent t) t :=
  ⟨hroot, rfl⟩

theorem existsUnique_parent {T : RootedTreeDecomposition G} {t : T.decomp.Node}
    (hroot : t ≠ T.root) :
    ∃! parent : T.decomp.Node, T.IsChild parent t := by
  refine ⟨T.parent t, isChild_parent hroot, ?_⟩
  intro parent hparent
  exact hparent.2

/-- `child` is the unique child of `t`. -/
def HasUniqueChild (T : RootedTreeDecomposition G) (t child : T.decomp.Node) : Prop :=
  T.IsChild t child ∧ ∀ child' : T.decomp.Node, T.IsChild t child' -> child' = child

/-- The reflexive descendant relation generated by children. -/
def IsAncestor (T : RootedTreeDecomposition G) (ancestor node : T.decomp.Node) : Prop :=
  Relation.ReflTransGen (fun parent child => T.IsChild parent child) ancestor node

/-- The node set of the subtree rooted at `t`. -/
def SubtreeNodes (T : RootedTreeDecomposition G) (t : T.decomp.Node) : Set T.decomp.Node :=
  {x | T.IsAncestor t x}

@[simp] theorem mem_subtreeNodes (T : RootedTreeDecomposition G)
    (t x : T.decomp.Node) :
    x ∈ T.SubtreeNodes t ↔ T.IsAncestor t x :=
  Iff.rfl

/-- The graph vertices appearing in bags of the subtree rooted at `t`. -/
def cone (T : RootedTreeDecomposition G) (t : T.decomp.Node) : Set V :=
  {v | ∃ x : T.decomp.Node, x ∈ T.SubtreeNodes t ∧ v ∈ T.bag x}

@[simp] theorem mem_cone (T : RootedTreeDecomposition G) (t : T.decomp.Node) (v : V) :
    v ∈ T.cone t ↔ ∃ x : T.decomp.Node, x ∈ T.SubtreeNodes t ∧ v ∈ T.bag x :=
  Iff.rfl

/--
`A` is the adhesion of `t`: the empty set at the root, and otherwise the
intersection of `t`'s bag with its parent's bag.
-/
def IsAdhesion (T : RootedTreeDecomposition G) (t : T.decomp.Node) (A : Set V) : Prop :=
  (t = T.root ∧ A = ∅) ∨
    (t ≠ T.root ∧ A = T.bag t ∩ T.bag (T.parent t))


open Classical in
/--
The adhesion of `t`: the empty set at the root, and otherwise the intersection
of `t`'s bag with a parent bag when a parent is available.
-/
noncomputable def adhesion (T : RootedTreeDecomposition G) (t : T.decomp.Node) : Set V :=
      if t = T.root then
        ∅
      else
        T.bag t ∩ T.bag (T.parent t)

lemma adhesion_isAdhesion (T : RootedTreeDecomposition G) (t : T.decomp.Node) :
  T.IsAdhesion t (adhesion T t) := by
  simp [adhesion,IsAdhesion]
  by_cases h : t= T.root<;>simp [h]

theorem root_isAdhesion_empty (T : RootedTreeDecomposition G) :
    T.IsAdhesion T.root (∅ : Set V) := by
  exact Or.inl ⟨rfl, rfl⟩

@[simp] theorem adhesion_root (T : RootedTreeDecomposition G) :
    T.adhesion T.root = (∅ : Set V) := by
  simp [adhesion]

theorem isAdhesion_of_isChild (T : RootedTreeDecomposition G) {parent t : T.decomp.Node}
    (hroot : t ≠ T.root) (hchild : T.IsChild parent t) :
    T.IsAdhesion t (T.bag t ∩ T.bag parent) := by
  exact Or.inr ⟨hroot, by rw [hchild.2]⟩


theorem adhesion_eq_inter_parent (T : RootedTreeDecomposition G)
    {t : T.decomp.Node} (hroot : t ≠ T.root) :
    T.adhesion t = T.bag t ∩ T.bag (T.parent t) := by
  simp [adhesion, hroot]

theorem adhesion_eq_inter_of_isChild (T : RootedTreeDecomposition G)
    {parent t : T.decomp.Node} (hchild : T.IsChild parent t) :
    T.adhesion t = T.bag t ∩ T.bag parent := by
  rw [adhesion_eq_inter_parent T hchild.1, hchild.2]

end RootedTreeDecomposition
